CREATE TABLE IF NOT EXISTS categories (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name TEXT NOT NULL UNIQUE,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS brands (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name TEXT NOT NULL UNIQUE,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS products (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  title TEXT NOT NULL,
  description TEXT NOT NULL,
  gender TEXT NOT NULL,
  price NUMERIC NOT NULL DEFAULT 0 CHECK (price >= 0),
  prev_price NUMERIC CHECK (prev_price >= 0),
  discount BOOLEAN NOT NULL DEFAULT 0,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  category_name TEXT NOT NULL DEFAULT 'Other',
  brand_name TEXT NOT NULL DEFAULT 'Angular Apparel',
  FOREIGN KEY (category_name) REFERENCES categories(name) ON DELETE
  SET DEFAULT,
    FOREIGN KEY (brand_name) REFERENCES brands(name) ON DELETE
  SET DEFAULT
);
CREATE TABLE IF NOT EXISTS product_images (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  product_id INTEGER NOT NULL,
  url TEXT NOT NULL,
  is_main BOOLEAN NOT NULL DEFAULT 0,
  sort_order INTEGER NOT NULL DEFAULT 0,
  FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE CASCADE
);