CREATE TABLE IF NOT EXISTS categories (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name TEXT NOT NULL UNIQUE,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS brands (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name TEXT NOT NULL UNIQUE,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS products (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  sku TEXT NOT NULL UNIQUE,
  name TEXT NOT NULL,
  description TEXT NOT NULL,
  price NUMERIC NOT NULL DEFAULT 0 CHECK (price >= 0),
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  category_id INTEGER,
  brand_id INTEGER,
  FOREIGN KEY (category_id) REFERENCES categories(id) ON DELETE
  SET NULL,
    FOREIGN KEY (brand_id) REFERENCES brands(id) ON DELETE
  SET NULL
);